"""create bank connections table

Revision ID: e5acffd6babb
Revises: f232f6d614f8
Create Date: 2026-06-20 21:05:32.495711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5acffd6babb'
down_revision: Union[str, Sequence[str], None] = 'f232f6d614f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), server_default='gocardless', nullable=False),
    sa.Column('requisition_id', sa.String(), nullable=False),
    sa.Column('agreement_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='CR', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_connections_id'), 'bank_connections', ['id'], unique=False)
    op.create_index(op.f('ix_bank_connections_requisition_id'), 'bank_connections', ['requisition_id'], unique=True)
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.drop_index(op.f('ix_bank_connections_requisition_id'), table_name='bank_connections')
    op.drop_index(op.f('ix_bank_connections_id'), table_name='bank_connections')
    op.drop_table('bank_connections')
    # ### end Alembic commands ###
